version: '3'

services:
  db:
    image: geographica/postgis:dev_diplodocus
    environment:
      - POSTGRES_PASSWD=fastapi
    ports:
      - "5432:5432"
  web:
    build: .
    command: uvicorn app.main:app --reload --host="0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:fastapi@db/postgres
    depends_on:
      - db