"""events

Revision ID: 132cc6c4ba82
Revises: cf738cd5da59
Create Date: 2020-03-10 08:41:53.284442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132cc6c4ba82'
down_revision = 'cf738cd5da59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('voivodeship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['voivodeship_id'], ['voivodeships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_voivodeships_area', 'voivodeships', ['area'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('events')
    # ### end Alembic commands ###
