"""voivodeships

Revision ID: cf738cd5da59
Revises: 
Create Date: 2020-03-09 11:38:29.078613

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cf738cd5da59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voivodeships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voivodeships')
    # ### end Alembic commands ###
